### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by johnish** [cronofy/cronofy-php#25]
I was looking to set this up in composer. I believe it would be easier to do this if their was a tag created so composer could use the tag as a version number.  Please let me know if you agree or have other suggestions on using composer for this project.

Thank you,
John

**Comment by magroski** [comment]
I believe that version tagging is a must in any professional project.

A couple weeks ago an update that changed the amount of params passed to the Cronofy constructor was released (version 0.12 to 0.13). However, thanks to the lack of tag versioning my code was broke and I had to rewrite every `new Cronofy()` call.

This wouldn't happen to composer users if tags could be used instead of "dev master".

**Comment by stephenbinns** [comment]
We added tags recently so this should be resolved now
