### ISSUE TITLE
Non Root Namespace

### ISSUE THREAD

**Issue by ababkov** [cronofy/cronofy-php#64]
Would be nice if all the classes were available under a non root namespace e.g. `Cronofy`. 

Probably requires a major version bump if you make that change though.

`\CurlRequest` and `\HttpRequest` in particular are maybe a bit worrying.

**Comment by TerenceJefferies** [comment]
https://github.com/cronofy/cronofy-php/pull/74 - Hopefully this one will help with this.

**Comment by CronofyMatt** [comment]
Hi and thank you for taking the time to open this issue, and apologies for the delay in getting back. I hope that you were able to solve this issue as I understand it has been some time since it was first opened.

Due to the age of this issue I am going to close it for now, however if you are still having problems please either re-open the ticket, create a new issue, or contact us at [support@cronofy.com](mailto:support@cronofy.com) where our support and engineering teams can help you out.

We will be updating our monitoring of issues being opened on repos to make sure we don’t let issues stagnate in future. We put a lot of time and effort into the quality of our products and this falls below the standards of support and care we offer elsewhere.
