### ISSUE TITLE
Post and delete request do not return responses

### ISSUE THREAD

**Issue by lekoala** [cronofy/cronofy-php#85]
Not sure if this is a problem for the sdk itself or on cronofy's end, but post and delete request return empty responses "" which is really odd. Get request are fine though, so it doesn't seem related to improper usage of the sdk.

By running a verbose curl call, this part seems relevant

...
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!\n
* We are completely uploaded and fine\n
< HTTP/2 202 \r\n
...

I thought that maybe it was an issue with HTTP2 so I tried forcing HTTP 1 but that doesn't work any better...

**Comment by lekoala** [comment]
@victor-cronofy is this expected? just got caught again by this issue today, it's really sad that i cannot know if my delete calls are working or not

**Comment by victor-cronofy** [comment]
Thanks for contacting us. Bear with me that I am not sure which endpoint you were hitting. However, as your first message stated that the endpoint responds with status `202`. [Here](https://docs.cronofy.com/developers/api/events/upsert-event) is the documentation of one of the endpoint that returns `202` for your reference.

For `202 Accepted`, it means Cronofy accepted the request and will fulfil it in background since most of the endpoints will need to communicate with external providers that Cronofy doesn't have the control. The benefit is that Cronofy can impose retry mechanism at the back until the create/update is completed without blocking the request. Thus, without the dependency, Cronofy can make fast response back to you. If you received `202 Accepted`, you can treat it as success and the changes will be made shortly at the provider side.

Hope the information help and I will close this issue since it shouldn't be the issue of the SDK.
I cannot cover all the cases here. For more questions about integration, please contact support@cronofy.com for a more dedicated support.
