### ISSUE TITLE
requestToken returns boolean instead of AccessToken and RefreshTokens

### ISSUE THREAD

**Issue by coatesjonathan** [cronofy/cronofy-php#93]
The requestToken function returns a boolean, instead of the actual refresh token and access token that needs to be saved for future use, as it states in the docs, issue is here:
https://github.com/cronofy/cronofy-php/blob/5bcb4d1b07da5dff7729701eef3d41b3a862412b/src/Cronofy.php#L297

**Comment by CronofyMatt** [comment]
Hi and thank you for taking the time to open this issue, and apologies for the delay in getting back. I hope that you were able to solve this issue as I understand it has been some time since it was first opened.

The `requestToken` function will either return `true` in the case of success and an error string if it fails. The access token, refresh token, expiry times, and token map are stored in public fields on the `Cronofy` object instance in the `accessToken`, `refreshToken`, `expiresIn` and `token` fields respectively.

Due to the age of this issue I am going to close it for now, however if you are still having problems please either re-open the ticket, create a new issue, or contact us at [support@cronofy.com](mailto:support@cronofy.com) where our support and engineering teams can help you out.

We will be updating our monitoring of issues being opened on repos to make sure we don’t let issues stagnate in future. We put a lot of time and effort into the quality of our products and this falls below the standards of support and care we offer elsewhere.
